package com.example.sha1generator

import android.os.Bundle
import android.os.PersistableBundle
import android.util.Log
import android.view.Menu
import android.view.MenuItem
import android.view.WindowManager
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.google.gson.GsonBuilder
import kotlinx.android.synthetic.main.activity_main.*
import org.json.JSONObject
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec


class MainActivity : AppCompatActivity() {

    companion object {
        const val staticSecretKey = "0xfbhb5Knea7DRaTz7gWdDgGCgg="
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        setUpUI()
        catchEvent()

    }

    override fun onCreateOptionsMenu(menu: Menu?): Boolean {
        val inflater = menuInflater
        inflater.inflate(R.menu.menu, menu)
        return true
    }

    override fun onOptionsItemSelected(item: MenuItem): Boolean {

        when (item.itemId) {
            R.id.clearMenu -> clearTexts()
        }
        return true
    }

    override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)
        outState.putString("jsonStr", edtJsonString.text.toString())
        outState.putString("secretStr", edtSecretKey.text.toString())
        outState.putString("signStr", tvSign.text.toString())
    }

    override fun onRestoreInstanceState(savedInstanceState: Bundle) {
        super.onRestoreInstanceState(savedInstanceState)
        edtJsonString.setText(savedInstanceState.getString("jsonStr"))
        edtSecretKey.setText(savedInstanceState.getString("secretStr"))
        tvSign.text = savedInstanceState.getString("signStr")
    }

    private fun setUpUI(){
        window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN)
        window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN)
    }

    private fun catchEvent(){

        btnGenerate.setOnClickListener {
            tvSign.text = "Sign"
            generateSign()
        }

    }

    private fun generateSign(){

        var jsonStr: String = if (edtJsonString.text.isNotBlank()){
            edtJsonString.text.toString()
        } else{
            getJsonFromObject(PaymentChannelRequest()).also {
                Toast.makeText(this, "Generated by default object", Toast.LENGTH_LONG).show()
            }
        }

        try {
            val queryStr = getQueryString(jsonStr)

            var secretKey = edtSecretKey.text.toString()
            if (secretKey.isNullOrBlank()) secretKey = staticSecretKey

            val mac = Mac.getInstance("HmacSHA1")
            val secret = SecretKeySpec(secretKey.toByteArray(), mac.algorithm)
            mac.init(secret)
            val bytes = mac.doFinal(queryStr.toByteArray())
            val sign = bytesToHex(bytes)

            showSign(sign.toString())
        }
        catch (e: Exception){
            Toast.makeText(this, e.localizedMessage, Toast.LENGTH_LONG).show()
            edtJsonString.text.clear()
        }

    }

    private fun bytesToHex(hashInBytes: ByteArray): String? {
        val sb = StringBuilder()
        for (b in hashInBytes) {
            sb.append(String.format("%02x", b))
        }
        return sb.toString()
    }

    private class PaymentChannelRequest {
        val language: String = "en"
        val merchantCode: String = "T05280001"
        val method: String = "get.payment.channel"
        val nonceStr: String = "11AB"
        val signType: String = "HmacSHA1"
        val version: String = "1.0"
    }

    private fun getJsonFromObject(`object`: Any): String {
        val gSon = GsonBuilder().serializeNulls().create()
        return gSon.toJson(`object`)
    }

    private fun getQueryString(unParsedString: String): String{
        val sb = StringBuilder()
        val json = JSONObject(unParsedString)
        val keys: Iterator<String> = json.keys()
        while (keys.hasNext()) {
            val key = keys.next()
            sb.append(key)
            sb.append("=")
            sb.append(json.get(key))
            if (keys.hasNext()) sb.append("&")
        }
        return sb.toString()
    }

    private fun showSign(sign: String) {
        tvSign.text = sign
    }

    private fun clearTexts(){
        edtJsonString.text.clear()
        edtSecretKey.text.clear()
        tvSign.text = "Sign"
        Toast.makeText(this, "Texts cleared", Toast.LENGTH_LONG).show()
    }

}
